-- 단일행함수
-- 날짜/시간처리함수

-- NOW ~~
SELECT
    NOW()
    , SYSDATE()
    , LOCALTIME(), LOCALTIME
    , LOCALTIMESTAMP(), LOCALTIMESTAMP;
    
-- CURDATE, CURRENT_DATE
SELECT
    CURDATE()
    , CURRENT_DATE(), CURRENT_DATE;
    
-- CURTIME, CURRENT_TIME
SELECT
    CURTIME()
    , CURRENT_TIME(), CURRENT_TIME;
    
-- ADDDATE, SUBDATE
SELECT
    CURDATE()
    , ADDDATE(CURDATE(), 1)
    , SUBDATE(CURDATE(), 1);

SELECT
    ADDDATE('2024-12-31', INTERVAL 2 DAY)
    , ADDDATE('2024-12-31', INTERVAL 2 MONTH)
    , ADDDATE('2024-12-31', INTERVAL 2 YEAR);

-- ADDTIME, SUBTIME
SELECT
    ADDTIME('09:00:00', 10)
    , ADDTIME('09:00:00', '1:30')
    , ADDTIME('09:00:00', '1:30:15')
    , SUBTIME('09:00:00', '1:0');

-- DATEDIFF, TIME DIFF
SELECT
    DATEDIFF('2025-07-29', NOW())
    , TIMEDIFF('17:50:50', CURTIME());

-- YEAR, MONTH, DAY, HOUR, MINUTE, SECOND,MICROSECOND
SELECT
    YEAR(CURDATE())
    , MONTH(CURDATE())
    , DAY(CURDATE());

SELECT
    HOUR(CURTIME())
    , MINUTE(CURTIME())
    , SECOND(CURTIME())
    , MICROSECOND(CURTIME());

-- DATE, TIME
SELECT
    DATE(NOW())
    , TIME(NOW());

-- EXTRACT
SELECT
    EXTRACT(YEAR_MONTH FROM NOW())
    , EXTRACT(DAY_HOUR FROM NOW());

-- DAYOFWEEK, MONTHNAME, DAYOFYEAR
SELECT
    DAYOFWEEK(CURDATE())
    , DAYOFMONTH(CURDATE())
    , DAYOFYEAR(CURDATE())
    , MONTHNAME(CURDATE());
    
-- LAST_DAY(날짜)
SELECT
    LAST_DAY(CURDATE())
    , LAST_DAY("2024-02-10");

-- MAKEDATE, MAKETIME
SELECT
    MAKEDATE(2025, 32)
    , MAKETIME(14,45,03);
    
-- PERIOD_ADD, PERIOD_DIFF
SELECT
    PERIOD_ADD(202404, 5)
    , PERIOD_DIFF(202409, 202404);

-- DATE_FORMAT()
SELECT
    NOW()
    , DATE_FORMAT(NOW(), '%y-%m-%d')
    , DATE_FORMAT(NOW(), '%Y/%m/%d')
    , DATE_FORMAT(NOW(), '%H,%i,%s')
    , DATE_FORMAT(NOW(), '%h:%i-%s(%W, %a)')
;

SELECT @@lc_time_names; -- 현재 시간포맷을 채크하는 시스템포맷
SET @@lc_time_names = 'kr_KR';